import {
  BookMarked,
  BookOpen,
  Brain,
  Calculator,
  FlaskConical,
  HeartPulse,
  Languages,
  Lightbulb,
  Monitor,
  Palette,
  PenTool,
  Sprout,
} from "lucide-react";
import type { ChildId, ChildProfile, MaterialType, QuizResult, Subject, UploadRecord, VisualLesson } from "./types";

export const children: ChildProfile[] = [
  {
    id: "jayadeep",
    name: "Jayadeep",
    role: "SON",
    grade: "Class 9",
    level: 8,
    avatar: "👦",
    languages: ["English", "Hindi", "Kannada"],
    focus: "CBSE 2026 • rebuild fundamentals • concept-first learning",
    color: "blue",
  },
  {
    id: "harini",
    name: "Harini",
    role: "Daughter",
    grade: "Class 2",
    level: 6,
    avatar: "👧",
    languages: ["English", "Kannada"],
    focus: "Stories • phonics • number sense • joyful activities",
    color: "pink",
  },
];

export const materialTypes: MaterialType[] = [
  "Textbook",
  "Academic Diary",
  "Homework",
  "Worksheet",
  "Question Paper",
  "Notes",
  "School Diary",
  "School PPT",
  "Activities",
  "Activity File",
  "Images",
  "Assessment File",
  "Project Work",
  "Exam Schedule",
  "Other",
];

export const subjects: Subject[] = [
  {
    slug: "maths",
    name: "Maths",
    icon: Calculator,
    color: "text-blue-700",
    bg: "bg-blue-50",
    border: "border-blue-200",
    description: "Numbers, fractions, algebra, geometry, and confidence with problem solving.",
    childIds: ["jayadeep", "harini"],
    chapters: ["Fractions", "Number Sense", "Algebra Basics", "Word Problems"],
  },
  {
    slug: "science",
    name: "Science",
    icon: FlaskConical,
    color: "text-green-700",
    bg: "bg-green-50",
    border: "border-green-200",
    description: "Visual explanations for physics, chemistry, biology, and daily-life science.",
    childIds: ["jayadeep"],
    chapters: ["Atoms", "Motion", "Our Environment", "Matter Around Us"],
  },
  {
    slug: "english",
    name: "English",
    icon: BookOpen,
    color: "text-purple-700",
    bg: "bg-purple-50",
    border: "border-purple-200",
    description: "Reading, grammar, writing, comprehension, phonics, and speaking practice.",
    childIds: ["jayadeep", "harini"],
    chapters: ["Nouns", "Reading Practice", "Writing Sentences", "Comprehension"],
  },
  {
    slug: "hindi",
    name: "Hindi",
    icon: Languages,
    color: "text-pink-700",
    bg: "bg-pink-50",
    border: "border-pink-200",
    description: "Vocabulary, grammar, reading, writing, and simple explanations.",
    childIds: ["jayadeep"],
    chapters: ["व्याकरण", "पठन अभ्यास", "लेखन अभ्यास"],
  },
  {
    slug: "kannada",
    name: "Kannada",
    icon: Languages,
    color: "text-amber-700",
    bg: "bg-amber-50",
    border: "border-amber-200",
    description: "Kannada reading, writing, vocabulary, and school support.",
    childIds: ["jayadeep", "harini"],
    chapters: ["ಸ್ವರಗಳು", "ಓದುವ ಅಭ್ಯಾಸ", "ಪದಗಳು"],
  },
  {
    slug: "social-science",
    name: "Social Science",
    icon: BookMarked,
    color: "text-orange-700",
    bg: "bg-orange-50",
    border: "border-orange-200",
    description: "History, geography, civics, maps, and exam-friendly revision.",
    childIds: ["jayadeep"],
    chapters: ["Maps", "Democracy", "India and the World", "Resources"],
  },
  {
    slug: "ct-ai",
    name: "CT / AI",
    icon: Brain,
    color: "text-cyan-700",
    bg: "bg-cyan-50",
    border: "border-cyan-200",
    description: "Computer thinking, coding basics, safe internet, and AI readiness.",
    childIds: ["jayadeep"],
    chapters: ["Computer Basics", "Algorithms", "What is AI?", "Digital Safety"],
  },
  {
    slug: "physical-education-and-well-being",
    name: "Physical Education and Well-being",
    icon: HeartPulse,
    color: "text-red-700",
    bg: "bg-red-50",
    border: "border-red-200",
    description: "Health, fitness, hygiene, safety, yoga, and practical well-being for school life.",
    childIds: ["jayadeep"],
    chapters: [
      "Health and Fitness",
      "Balanced Diet",
      "Personal Hygiene",
      "Physical Activities",
      "Mental Well-being",
      "Yoga and Exercise",
      "Safety and First Aid",
    ],
  },
  {
    slug: "skill-education",
    name: "Skill Education",
    icon: Lightbulb,
    color: "text-yellow-700",
    bg: "bg-yellow-50",
    border: "border-yellow-200",
    description: "Practical communication, digital literacy, teamwork, creativity, and career-ready school skills.",
    childIds: ["jayadeep"],
    chapters: [
      "Communication Skills",
      "Digital Literacy",
      "Basic IT Skills",
      "Problem Solving",
      "Teamwork",
      "Creativity",
      "Career Awareness",
    ],
  },
  {
    slug: "arts",
    name: "Arts",
    icon: Palette,
    color: "text-fuchsia-700",
    bg: "bg-fuchsia-50",
    border: "border-fuchsia-200",
    description: "Drawing, colour, craft, creative expression, Indian art forms, posters, and art appreciation.",
    childIds: ["jayadeep"],
    chapters: [
      "Drawing Basics",
      "Colour Theory",
      "Craft Work",
      "Creative Expression",
      "Indian Art Forms",
      "Poster Making",
      "Art Appreciation",
    ],
  },
  {
    slug: "evs",
    name: "EVS",
    icon: Sprout,
    color: "text-emerald-700",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    description: "Plants, animals, home, school, habits, and the world around us.",
    childIds: ["harini"],
    chapters: ["Good Habits", "Water Cycle", "Plants", "My Family"],
  },
  {
    slug: "reading",
    name: "Reading",
    icon: BookOpen,
    color: "text-indigo-700",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    description: "Phonics, sight words, short stories, and reading fluency.",
    childIds: ["harini"],
    chapters: ["Phonics", "Sight Words", "Story Time", "Read Aloud"],
  },
  {
    slug: "writing",
    name: "Writing",
    icon: PenTool,
    color: "text-rose-700",
    bg: "bg-rose-50",
    border: "border-rose-200",
    description: "Handwriting, sentence formation, small paragraphs, and creative prompts.",
    childIds: ["harini"],
    chapters: ["Letters", "Simple Words", "Sentences", "My First Paragraph"],
  },
  {
    slug: "computer",
    name: "Computer",
    icon: Monitor,
    color: "text-cyan-700",
    bg: "bg-cyan-50",
    border: "border-cyan-200",
    description: "Computer parts, keyboard practice, and basic digital awareness.",
    childIds: ["harini"],
    chapters: ["Computer Parts", "Keyboard", "Mouse Practice", "Internet Safety"],
  },
];

export const learningModes = [
  "Teach from basics",
  "Explain in simple English",
  "Explain with Telugu support",
  "Explain like a story",
  "Give real-life examples",
  "Prepare for test",
  "Ask me questions",
  "Make it visual",
];

export const mockUploads: UploadRecord[] = [
  {
    id: "seed-1",
    fileName: "Maths Chapter 3 Notes.pdf",
    childId: "jayadeep",
    grade: "Class 9",
    subject: "Maths",
    materialType: "Notes",
    chapter: "Fractions",
    notes: "School revision notes",
    status: "Ready for AI indexing",
    source: "Local Upload",
    indexStatus: "Uploaded",
    sizeLabel: "2.4 MB",
    uploadedAt: "Today",
  },
  {
    id: "seed-2",
    fileName: "Science Chapter 2.pptx",
    childId: "jayadeep",
    grade: "Class 9",
    subject: "Science",
    materialType: "School PPT",
    chapter: "Our Environment",
    notes: "Teacher PPT",
    status: "Uploaded",
    source: "Local Upload",
    indexStatus: "Uploaded",
    sizeLabel: "5.1 MB",
    uploadedAt: "Yesterday",
  },
  {
    id: "seed-3",
    fileName: "English Grammar.pdf",
    childId: "harini",
    grade: "Class 2",
    subject: "English",
    materialType: "Worksheet",
    chapter: "Nouns",
    notes: "Grammar practice",
    status: "Indexed",
    source: "Local Upload",
    indexStatus: "Indexed",
    sizeLabel: "1.8 MB",
    uploadedAt: "2 days ago",
  },
  {
    id: "seed-4",
    fileName: "Academic Diary - April.pdf",
    childId: "jayadeep",
    grade: "Class 9",
    subject: "General",
    materialType: "Academic Diary",
    chapter: "April",
    notes: "Diary snapshot",
    status: "Needs Review",
    source: "Local Upload",
    indexStatus: "Uploaded",
    sizeLabel: "1.2 MB",
    uploadedAt: "3 days ago",
  },
];

export const mockVisualLesson: VisualLesson = {
  title: "Fractions Made Visual",
  gradeLevel: "Class 9 foundation recovery",
  slides: [
    {
      slideType: "hook",
      title: "What does one part of a whole look like?",
      teacherScript: "A fraction is a way to show selected equal parts of one whole. We first see the whole, then we count the equal parts.",
      visualType: "two-column-card",
      visualData: {
        leftTitle: "Whole",
        leftExamples: ["One complete bar", "One complete circle"],
        rightTitle: "Parts",
        rightExamples: ["1 out of 4 equal parts", "3 out of 8 equal parts"],
      },
      keyPoints: ["Fractions start with one whole.", "The parts must be equal."],
    },
    {
      slideType: "definition",
      title: "Fraction form",
      teacherScript: "A fraction has a top number and a bottom number. The top number tells selected parts. The bottom number tells total equal parts.",
      visualType: "formula-card",
      visualData: {
        formula: "selected parts / total equal parts",
        validFor: "2/8 means 2 selected parts out of 8 equal parts.",
        notValidFor: "Unequal pieces cannot be named fairly with one simple fraction.",
      },
      keyPoints: ["Top number is selected parts.", "Bottom number is total equal parts."],
    },
    {
      slideType: "quick-check",
      title: "Quick check",
      teacherScript: "If a shape has 8 equal parts and 2 parts are shaded, the fraction is 2 by 8.",
      visualType: "quiz-card",
      visualData: {
        question: "A cake has 8 equal slices. You eat 2 slices. What fraction did you eat?",
        options: ["2/8", "8/2", "1/8", "2"],
        correctAnswer: "2/8",
        explanation: "The selected parts are 2 and the total equal parts are 8.",
      },
      keyPoints: ["Selected parts go on top.", "Total equal parts go below."],
      studentQuestion: "What number should go below the line?",
      answer: "The total number of equal parts.",
    },
  ],
};

export const mockQuiz: QuizResult = {
  title: "Starter Concept Quiz",
  questions: [
    {
      question: "What does the denominator show in a fraction?",
      options: ["Selected parts", "Total equal parts", "Only big numbers", "Marks scored"],
      answer: "Total equal parts",
      explanation: "The denominator is the bottom number and shows how many equal parts the whole has.",
    },
    {
      question: "Which is a real-life example of a fraction?",
      options: ["A whole pencil", "Half a sandwich", "A school bell", "A full notebook only"],
      answer: "Half a sandwich",
      explanation: "Half means 1 out of 2 equal parts, so it is a fraction.",
    },
  ],
};

export function getChild(id: ChildId) {
  return children.find((child) => child.id === id) || children[0];
}

export function getSubjectsForChild(childId: ChildId) {
  return subjects.filter((subject) => subject.childIds.includes(childId));
}

export function getSubjectBySlug(slug: string) {
  return subjects.find((subject) => subject.slug === slug) || subjects[0];
}
